services:
  - type: web
    name: venbrax-api
    env: node
    plan: free
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: node dist/main.js
    envVars:
      - key: PORT
        value: 3001
  - type: web
    name: venbrax-web
    env: static
    rootDir: apps/web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
